### ISSUE TITLE
Seems not to work on Windows

### ISSUE THREAD

**Issue by Dimsok** [motiz88/vlc-plugin-sapispeechsynthesizer#1]
I copy dll from releases to plugs, open in vlc speechsynth settings, but there only options with digits like -32, 42 etc, How to use it? Doesn't read any subs.

**Comment by motiz88** [comment]
Hey @Dimsok! A version of this plugin has actually been part of the VLC codebase [since 2015](https://github.com/videolan/vlc/commits/master/modules/text_renderer/sapi.cpp). There is likely no need to build it separately anymore. Please check the main VLC [repository](https://github.com/videolan/vlc) for any issues you're having with the built-in SAPI speech synthesiser. Hope that helps!
